CREATE TABLE estoque (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     sku VARCHAR(100) NOT NULL UNIQUE,
     quantidade INT NOT NULL DEFAULT 0,
     atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE estoque
    ADD CONSTRAINT uk_estoque_sku UNIQUE (sku);